services:
  app:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile.dev
    container_name: opspulse-app
    profiles:
      - app
    restart: unless-stopped
    command: air -c .air.app.toml
    env_file:
      - ../.env
    working_dir: /app
    volumes:
      - go-pkg-mod:/go/pkg/mod
      - ..:/app

  api:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile.dev
      args:
        TARGET_AIR: -c .air.api.toml
    container_name: opspulse-api
    profiles:
      - api
    restart: unless-stopped
    command: air -c .air.api.toml
    env_file:
      - ../.env
    working_dir: /app
    ports:
      - 3333:3333
    volumes:
      - ..:/app
      - go-pkg-mod:/go/pkg/mod

volumes:
  go-pkg-mod:
