services:
  app:
    build:
      context: ../
      dockerfile: ./build/package/go/Dockerfile.dev
    container_name: opspulse-app
    profiles:
      - app
      - dev
    restart: unless-stopped
    command: air -c .air.app.toml
    env_file:
      - ../.env
    working_dir: /app
    volumes:
      - go-pkg-mod:/go/pkg/mod
      - ..:/app

  api:
    build:
      context: ../
      dockerfile: ./build/package/go/Dockerfile.dev
      args:
        TARGET_AIR: -c .air.api.toml
    container_name: opspulse-api
    profiles:
      - api
      - dev
    restart: unless-stopped
    command: air -c .air.api.toml
    env_file:
      - ../.env
    working_dir: /app
    ports:
      - 3333:3333
    volumes:
      - ..:/app
      - go-pkg-mod:/go/pkg/mod

  vite:
    build:
      context: ../web/opspulse-frontend
      dockerfile: ../../build/package/vite/Dockerfile.dev
    container_name: vite_app
    profiles:
      - api
      - frontend
      - dev
    ports:
      - "5174:5173"
    volumes:
      - ../web/opspulse-frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true

  mongodb:
    image: mongo:7.0
    container_name: opspulse-mongodb
    profiles:
      - api
      - dev
      - database
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=opspulse
    volumes:
      - mongodb-data:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - "8097:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always
    profiles:
      - api
      - dev
      - database

volumes:
  go-pkg-mod:
  mongodb-data:
