services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: opspulse-app
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./log:/app/log
      